sudo: false
dist: trusty
language: java
jdk:
  - oraclejdk8
script:
  - "./mvnw org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -B"
notifications:
  email:
    recipients:
      - skypencil+travis@gmail.com
addons:
  sonarcloud:
    organization: "kengotoda-github"
    token:
      secure: "f1Z4IVsM0ES/J8qef/uelzIzYlJmyhDNBWW1MOlaSfUExPcIVD/X4NFpVOB8dyGFUtc7yvhDjnDWoqSs4dG/iQReR1M8g6EwoM74t7AKPVaXMbeuFImBRZP2hbNiEjUFGaDab4r+A/sGjSHT+LpKtDuyV49TSeuaUVPAYrHQ4xXJp4ux3AHFJielxAlT9lWg72E3j65V02UJTT4pPu0x/GWpH/1tYZosTdowm1b59PKUFNLwfQ+NcnUvt1aiyJEbZF1ZFr/jbXD5gVOpynTm5mMWbWG3QaxIGVONuiIR5kSKWYNvEi8Iof47pCuyRmeCGMwDqppQ/5EiNbPBToGcIhWcWApqU7Dw7dipyF843gNNwAJIC/4WG5C2kO8DHJOZERLCm2TbRnimR+OdB+1345blVlsoYUC8THgY9FZp8RNXplH8K7hlewnnyRjya3pRYoNl+J512ROGfLKjUP+1ok18qKf9nqiS8zX6kKGFgpfO98NyH9e7mzREk959YZKAjVImXllZxXQ5seIEqUzfdZDlNgMRgIEG5VKXfNcZZbx2q4uFoxGGZtx+LCrIqxXZ2wwJOhK0tk3xUrhXO7Y4eiANmlTJyVWei6BjXFEs2M/eljCVLdT8mp15HTnuw3v3xQ+ngY9qGQWKweX9z9UyqhAkYFE2T8bvHK1QkZKRkr8="
